export const userRelated = {
    SIGNIN_REQUEST: 'USER_SIGNIN_REQUEST',
    SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
    SIGNIN_FAILURE: 'USER_SIGNIN_FAILURE',
    SIGNOUT: 'USER_SIGNOUT',
    REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    
    
    
    
    
}
